### ISSUE TITLE
Out of memory error when summing large sequence

### ISSUE THREAD

**Issue by lthiet** [RumbleDB/rumble#1075]
Done on Rumble 1.14, ran from :

```
$ spark-submit rumbledb-1.14.0-for-spark-2.jar --shell yes --print-error-info yes
```

```
RumbleDB$ sum(1 to 134217728)
>>> 
>>> 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:238)
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at org.rumbledb.runtime.RuntimeIterator.materialize(RuntimeIterator.java:276)
	at org.rumbledb.runtime.functions.sequences.aggregate.SumFunctionIterator.computeLocally(SumFunctionIterator.java:128)
	at org.rumbledb.runtime.functions.sequences.aggregate.SumFunctionIterator.computeSum(SumFunctionIterator.java:113)
	at org.rumbledb.runtime.functions.sequences.aggregate.SumFunctionIterator.open(SumFunctionIterator.java:62)
	at org.rumbledb.api.SequenceOfItems.populateList(SequenceOfItems.java:140)
	at org.rumbledb.cli.JsoniqQueryExecutor.runInteractive(JsoniqQueryExecutor.java:193)
	at org.rumbledb.shell.RumbleJLineShell.processQuery(RumbleJLineShell.java:95)
	at org.rumbledb.shell.RumbleJLineShell.launch(RumbleJLineShell.java:80)
	at org.rumbledb.cli.Main.launchShell(Main.java:191)
	at org.rumbledb.cli.Main.main(Main.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by ingomueller-net** [comment]
Lam and I ran into this problem together. To me it seems like it should be possible to execute this query with materializing intermediate results (which is apparently what happens, see `org.rumbledb.runtime.RuntimeIterator.materialize` in the stacktrace).

**Comment by ghislainfourny** [comment]
Very good point! It would be a nice optimization. Thank you for the finding.

**Comment by ingomueller-net** [comment]
Which commit is this? v1.16.0 still has this problem.

**Comment by ghislainfourny** [comment]
@ingomueller-net @lthiet it seems to work on the latest release, do you confirm?
