### ISSUE TITLE
"An error has occurred: null"

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#651]
The following expression causes Rumble to throw an unknown error:

```xquery
let $a := 42 group by $a return $a
```

**Comment by ghislainfourny** [comment]
Thanks, Ingo! In general, you can add --show-error-info yes if you want to also copy-paste exception stacks to issues.

**Comment by ghislainfourny** [comment]
I cannot reproduce the error -- I think your stacktrace would be very useful.

**Comment by ingomueller-net** [comment]
I just updated to the latest master (378e3db). This is what I get:

```
rumble$ let $a := 42 group by $a return $a
>>>
>>>
An error has occurred: null
We should investigate this 🙈. Please contact us or file an issue on GitHub with your query.
Link: https://github.com/RumbleDB/rumble/issues
java.lang.NullPointerException
        at org.rumbledb.expressions.flowr.GroupByClause.print(GroupByClause.java:84)
        at org.rumbledb.expressions.flowr.Clause.print(Clause.java:104)
        at org.rumbledb.expressions.Node.print(Node.java:156)
        at org.rumbledb.expressions.Node.print(Node.java:156)
        at org.rumbledb.expressions.Node.toString(Node.java:163)
        at java.lang.String.valueOf(String.java:2994)
        at java.io.PrintStream.println(PrintStream.java:821)
        at org.rumbledb.cli.JsoniqQueryExecutor.runInteractive(JsoniqQueryExecutor.java:123)
        at org.rumbledb.shell.RumbleJLineShell.processQuery(RumbleJLineShell.java:88)
        at org.rumbledb.shell.RumbleJLineShell.launch(RumbleJLineShell.java:74)
        at org.rumbledb.cli.Main.launchShell(Main.java:124)
        at org.rumbledb.cli.Main.main(Main.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by ingomueller-net** [comment]
Ah! It's only about the printing! If you don't run with `--print-iterator-tree yes`, it works.

How about running all your tests also with that option to make sure the printing at least runs...

**Comment by ghislainfourny** [comment]
This should now be fixed as well. Tests are now executed with print-iterator-tree set to yes.
