### ISSUE TITLE
Allow rounded results for avg

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#764]
I cannot make the following query work:

```xquery
avg((3,3,4))
```

The error is:

```
An error has occurred: Non-terminating decimal expansion; no exact representable decimal result.
We should investigate this 🙈. Please contact us or file an issue on GitHub with your query.
Link: https://github.com/RumbleDB/rumble/issues
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
        at java.math.BigDecimal.divide(BigDecimal.java:1693)
        at org.rumbledb.runtime.functions.sequences.aggregate.AvgFunctionIterator.next(AvgFunctionIterator.java:86)
...
```

Is this really the intended behavior?

**Comment by ingomueller-net** [comment]
BTW, this also happens if I cast the numbers to double:

```xquery
avg((double(3),double(3),double(4))
```

The error message is the same, so the calculations are apparently carried out using `BigDecimal` as well. Again, is this the intended behavior?

**Comment by ghislainfourny** [comment]
duplicate with #771 . Duplicate bugs are a very good sign because it means we are maturing.

**Comment by ghislainfourny** [comment]
#773

**Comment by ghislainfourny** [comment]
And fixed!

**Comment by ingomueller-net** [comment]
I guess this issue can be closed then?
