### ISSUE TITLE
Rumble API crash

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#805]
Running following code with Rumble API crashes the whole application without catching the exception:
```
try{
SequenceOfItems queryResult = rumbleInstance.runQuery("json-doc("http://www.example.org/#fragment")");
List<Item> resultAsList = new ArrayList<>();
queryResult.populateListWithWarningOnlyIfCapReached(resultAsList);
}
catch (Exception e){
}
```

Console log:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/ml/linalg/VectorUDT
	at org.rumbledb.runtime.functions.io.JsonDocFunctionIterator.next(JsonDocFunctionIterator.java:78)
	at org.rumbledb.api.SequenceOfItems.populateList(SequenceOfItems.java:143)
	at org.rumbledb.api.SequenceOfItems.populateListWithWarningOnlyIfCapReached(SequenceOfItems.java:177)
	at ch.ethz.TestDriver.runQuery(TestDriver.java:551)
	at ch.ethz.TestDriver.processTestCase(TestDriver.java:255)
	at ch.ethz.TestDriver.processTestSet(TestDriver.java:149)
	at ch.ethz.TestDriver.processCatalog(TestDriver.java:124)
	at ch.ethz.TestDriver.execute(TestDriver.java:45)
	at ch.ethz.Run.main(Run.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.linalg.VectorUDT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more

**Comment by mstevan** [comment]
Adding dependency to Rumble does not work always well via Maven. For unknown reason, even though the dependencies are clearly defined in pom.xml of Rumble, when referencing it in your own Java Application the following dependencies need to be manually added to pom.xml of your Java Application:
<dependency>
            <groupId>org.jgrapht</groupId>
            <artifactId>jgrapht-core</artifactId>
            <version>1.4.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>1.6</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.jsoniter</groupId>
            <artifactId>jsoniter</artifactId>
            <version>0.9.19</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.11</artifactId>
            <version>2.4.4</version>
            <scope>compile</scope>
        </dependency>
