### ISSUE TITLE
java.lang.ClassFormatError: class com.jsoniter.IterImpl cannot access its superclass

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#807]
Since 1.9.0, Rumble does not work in the docker environment anymore:

```
$ docker run --rm -it rumbledb/rumble:v1.9.0-spark3 --shell yes
20/11/16 13:23:40 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
An error has occured: javassist.CannotCompileException: by java.lang.ClassFormatError: class com.jsoniter.IterImpl cannot access its superclass com.jsoniter.IterImplForStreaming
We should investigate this 🙈. Please contact us or file an issue on GitHub with your query.
```

The same problem happens with earlier versions opening a json file containing `{}`:

```
rumble$ json-doc("/data/test.json")
>>>
>>>
An error has occurred: javassist.CannotCompileException: by java.lang.ClassFormatError: class com.jsoniter.IterImpl cannot access its superclass com.jsoniter.IterImplForStreaming
We should investigate this 🙈. Please contact us or file an issue on GitHub with your query.
Link: https://github.com/RumbleDB/rumble/issues
com.jsoniter.spi.JsonException: javassist.CannotCompileException: by java.lang.ClassFormatError: class com.jsoniter.IterImpl cannot access its superclass com.jsoniter.IterImplForStreaming
        at com.jsoniter.JsonIterator.enableStreamingSupport(JsonIterator.java:534)
        at com.jsoniter.JsonIterator.parse(JsonIterator.java:68)
        at org.rumbledb.runtime.functions.io.JsonDocFunctionIterator.next(JsonDocFunctionIterator.java:77)
        at org.rumbledb.api.SequenceOfItems.populateList(SequenceOfItems.java:117)
        at org.rumbledb.cli.JsoniqQueryExecutor.runInteractive(JsoniqQueryExecutor.java:145)
        at org.rumbledb.shell.RumbleJLineShell.processQuery(RumbleJLineShell.java:95)
        at org.rumbledb.shell.RumbleJLineShell.launch(RumbleJLineShell.java:80)
        at org.rumbledb.cli.Main.launchShell(Main.java:141)
        at org.rumbledb.cli.Main.main(Main.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: javassist.CannotCompileException: by java.lang.ClassFormatError: class com.jsoniter.IterImpl cannot access its superclass com.jsoniter.IterImplForStreaming
        at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:271)
        at javassist.ClassPool.toClass(ClassPool.java:1232)
        at javassist.ClassPool.toClass(ClassPool.java:1090)
        at javassist.ClassPool.toClass(ClassPool.java:1048)
        at javassist.CtClass.toClass(CtClass.java:1290)
        at com.jsoniter.DynamicCodegen.enableStreamingSupport(DynamicCodegen.java:32)
        at com.jsoniter.JsonIterator.enableStreamingSupport(JsonIterator.java:530)
        ... 20 more
Caused by: java.lang.ClassFormatError: class com.jsoniter.IterImpl cannot access its superclass com.jsoniter.IterImplForStreaming
        at javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:182)
        at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
        ... 26 more
```

The same problem seems to be reported [here](https://github.com/json-iterator/java/issues/225) and [here](https://github.com/json-iterator/java/issues/227) with no mentioning of docker, so I don't think that it is specific to being run in docker but rather to the Java version/configuration incidentally being used there.

**Comment by ghislainfourny** [comment]
Release 1.9.1 adds a CLI flag --deactivate-jsoniter-streaming that circumvents this issue.
