### ISSUE TITLE
Runtime operator cannot be opened twice

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#809]
The following query:

```xquery
declare function f() { 1 to 10 };
for $j in 1 to 10
where empty(f())
return $j
```

produces the following error on 1.8.1 (1.9.0 doesn't work for me due to #807):

```
⚠️  ️There was an error.

Code: [RBST0004] (this code can be looked up in the documentation and specifications).

Location information: file:/var/spark/:LINE:3:COLUMN:12:

Runtime iterator cannot be opened twice
org.rumbledb.exceptions.IteratorFlowException: There was an error.

Code: [RBST0004] (this code can be looked up in the documentation and specifications).

Location information: file:/var/spark/:LINE:3:COLUMN:12:

Runtime iterator cannot be opened twice
        at org.rumbledb.runtime.RuntimeIterator.open(RuntimeIterator.java:178)
        at org.rumbledb.runtime.HybridRuntimeIterator.open(HybridRuntimeIterator.java:64)
        at org.rumbledb.runtime.functions.StaticUserDefinedFunctionCallIterator.openLocal(StaticUserDefinedFunctionCallIterator.java:74)
        at org.rumbledb.runtime.HybridRuntimeIterator.open(HybridRuntimeIterator.java:66)
        at org.rumbledb.runtime.functions.sequences.general.EmptyFunctionIterator.next(EmptyFunctionIterator.java:56)
        at org.rumbledb.runtime.operational.TypePromotionIterator.setNextResult(TypePromotionIterator.java:86)
        at org.rumbledb.runtime.operational.TypePromotionIterator.openLocal(TypePromotionIterator.java:68)
        at org.rumbledb.runtime.HybridRuntimeIterator.open(HybridRuntimeIterator.java:66)
        at org.rumbledb.runtime.flwor.clauses.WhereClauseSparkIterator.setNextLocalTupleResult(WhereClauseSparkIterator.java:129)
        at org.rumbledb.runtime.flwor.clauses.WhereClauseSparkIterator.open(WhereClauseSparkIterator.java:74)
        at org.rumbledb.runtime.flwor.clauses.ReturnClauseSparkIterator.openLocal(ReturnClauseSparkIterator.java:165)
        at org.rumbledb.runtime.HybridRuntimeIterator.open(HybridRuntimeIterator.java:66)
        at org.rumbledb.api.SequenceOfItems.populateList(SequenceOfItems.java:114)
        at org.rumbledb.cli.JsoniqQueryExecutor.runInteractive(JsoniqQueryExecutor.java:145)
        at org.rumbledb.shell.RumbleJLineShell.processQuery(RumbleJLineShell.java:95)
        at org.rumbledb.shell.RumbleJLineShell.launch(RumbleJLineShell.java:80)
        at org.rumbledb.cli.Main.launchShell(Main.java:141)
        at org.rumbledb.cli.Main.main(Main.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by ingomueller-net** [comment]
I confirm that the example from this issue works now :) Thanks!
