### ISSUE TITLE
Invalid SQL generated when querying Parquet file

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#919]
Consider the following query:

```xquery
let $filtered :=
  for $event in parquet-file("/path/file.parquet")
  return {"event": $event.blup, "tj": [1 to 5]}
for $event in $filtered
order by $event.tj.pt
return $event
```

When I run this (against any Parquet file), I get the following:

```
An error has occured:
missing ')' at 'order'(line 1, pos 109)

== SQL ==
select `event` from (select `event`, createOrderingColumns(struct(`event`)) as `ordering_columns` from input order by )
-------------------------------------------------------------------------------------------------------------^^^

We should investigate this 🙈. Please contact us or file an issue on GitHub with your query.
Link: https://github.com/RumbleDB/rumble/issues
For more debug info (e.g., so you can communicate it to us), please try again using --show-error-info yes in your command line.
org.apache.spark.sql.catalyst.parser.ParseException:
missing ')' at 'order'(line 1, pos 109)

== SQL ==
select `event` from (select `event`, createOrderingColumns(struct(`event`)) as `ordering_columns` from input order by )
-------------------------------------------------------------------------------------------------------------^^^

        at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:266)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:133)
        at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:81)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:605)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:605)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
        at org.rumbledb.runtime.flwor.clauses.OrderByClauseSparkIterator.getDataFrame(OrderByClauseSparkIterator.java:424)
        at org.rumbledb.runtime.flwor.clauses.ReturnClauseSparkIterator.getRDDAux(ReturnClauseSparkIterator.java:111)
        at org.rumbledb.runtime.HybridRuntimeIterator.getRDD(HybridRuntimeIterator.java:135)
        at org.rumbledb.api.SequenceOfItems.populateListWithWarningOnlyIfCapReached(SequenceOfItems.java:174)
        at org.rumbledb.cli.JsoniqQueryExecutor.runQuery(JsoniqQueryExecutor.java:151)
        at org.rumbledb.cli.Main.runQueryExecutor(Main.java:152)
        at org.rumbledb.cli.Main.main(Main.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Note that if you replace `parquet-file` with `json-file` (and an appropriate path), the error goes away.

**Comment by ghislainfourny** [comment]
@ingomueller-net does it still have the issue with the master? It reminds me of another bug that was solved.

**Comment by ingomueller-net** [comment]
The query runs indeed with 3db7000b1. (Today's master produces another error; maybe you dropped Spark 2 support?) Does that commit include the fix you were thinking of? If yes, I think we can close this issue.

**Comment by ghislainfourny** [comment]
Thank you for confirming, Ingo!
